
export const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
